name: Update menu (on-prem docker)

on:
  schedule:
    # Ajaa arkipäivisin klo 03:35 UTC (klo 06:35 Suomen aikaa)
    # Herää minuutilleen oikeaan aikaan omalla palvelimellasi
    - cron: "35 3 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted # Ohjaa työn omalle palvelimellesi
    
    # TÄMÄ AJAA VAIHEET DOCKER-KONTISSA:
    container:
      image: node:20-alpine

    steps:
      # Alpine tarvitsee gitin, jotta checkout ja push toimivat kontin sisältä
      - name: Install Git
        run: apk add --no-cache git

      - uses: actions/checkout@v4

      - name: Install and Scrape
        run: |
          npm install
          node scrape.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add -A
          
          git commit -m "update menu on-prem docker $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          
          git push
